default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: capfat_development

test:
  <<: *default
  database: capfat_test

production:
  <<: *default
  database: capfat_production
  username: capfat
  password: <%= ENV["CAPFAT_DATABASE_PASSWORD"] %>
